version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 10
      runas: root
    - location: scripts/ApplicationStart.sh
      timeout: 10
      runas: root
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 10
      runas: root
