version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: ApplicationStart.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: AfterInstall.sh
      timeout: 10
      runas: root
